# Generated by Django 4.2.6 on 2023-10-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poll',
            table='polls',
        ),
    ]
